// Generates Android resources from brand/flow-reader-mark.svg. Run: node brand/build.mjs
// Supports only what the master uses: <path d fill stroke stroke-width stroke-linejoin> in
// #background / #foreground, userSpaceOnUse linear/radial gradients whose stops are
// `stop-color: var(--name, #hex)`.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const res = join(here, '..', 'app', 'src', 'main', 'res');
const svg = readFileSync(join(here, 'flow-reader-mark.svg'), 'utf8').replace(/<!--[\s\S]*?-->/g, '');

const attrs = (s) => Object.fromEntries([...s.matchAll(/([\w:-]+)="([^"]*)"/g)].map((m) => [m[1], m[2]]));
const squash = (d) => d.replace(/\s+/g, ' ').trim();

function argb(hex) {
  const h = hex.replace('#', '').toUpperCase();
  if (h.length === 6) return `#FF${h}`;
  if (h.length === 8) return `#${h.slice(6)}${h.slice(0, 6)}`;
  throw new Error(`Unsupported colour ${hex}`);
}

const gradients = {};
const colors = {};
for (const m of svg.matchAll(/<(linear|radial)Gradient\s([^>]*)>([\s\S]*?)<\/\1Gradient>/g)) {
  const a = attrs(m[2]);
  if (a.gradientUnits !== 'userSpaceOnUse') throw new Error(`${a.id}: gradientUnits must be userSpaceOnUse`);
  const stops = [...m[3].matchAll(/<stop\s([^>]*)\/>/g)].map((s) => {
    const sa = attrs(s[1]);
    const v = /var\(--([\w-]+),\s*(#[0-9a-fA-F]+)\)/.exec(sa.style ?? '');
    if (!v) throw new Error(`${a.id}: stop needs stop-color: var(--name, #hex)`);
    colors[v[1]] = v[2];
    return { offset: sa.offset, color: argb(v[2]) };
  });
  gradients[a.id] = { type: m[1], ...a, stops };
}

function layer(id) {
  const g = new RegExp(`<g id="${id}">([\\s\\S]*?)</g>`).exec(svg);
  if (!g) throw new Error(`Missing <g id="${id}">`);
  return [...g[1].matchAll(/<path\s([\s\S]*?)\/>/g)].map((p) => {
    const a = attrs(p[1]);
    return { ...a, d: squash(a.d) };
  });
}

/** `value` is an SVG paint (`#hex` or `url(#id)`); `name` is fillColor or strokeColor. */
function paint(value, name) {
  const ref = /url\(#([\w-]+)\)/.exec(value);
  if (!ref) return { attr: `android:${name}="${argb(value)}"`, body: '' };
  const g = gradients[ref[1]];
  const geo = g.type === 'linear'
    ? `android:type="linear" android:startX="${g.x1}" android:startY="${g.y1}" android:endX="${g.x2}" android:endY="${g.y2}"`
    : `android:type="radial" android:centerX="${g.cx}" android:centerY="${g.cy}" android:gradientRadius="${g.r}"`;
  const items = g.stops.map((s) => `                <item android:offset="${s.offset}" android:color="${s.color}" />`).join('\n');
  return {
    attr: '',
    body: `
        <aapt:attr name="android:${name}">
            <gradient ${geo}>
${items}
            </gradient>
        </aapt:attr>`,
  };
}

function fill(path) {
  const parts = [paint(path.fill, 'fillColor')];
  if (path.stroke) {
    parts.push(paint(path.stroke, 'strokeColor'));
    parts.push({ attr: `android:strokeWidth="${path['stroke-width'] ?? 1}"`, body: '' });
    if (path['stroke-linejoin']) parts.push({ attr: `android:strokeLineJoin="${path['stroke-linejoin']}"`, body: '' });
  }
  const attr = parts.map((p) => p.attr).filter(Boolean).join('\n        ');
  const body = parts.map((p) => p.body).join('');
  return { attr, body: body ? `${body}\n    ` : '' };
}

function pathXml(d, fillAttr, body = '', extra = '') {
  const open = `    <path${extra}\n        android:pathData="${d}"${fillAttr ? `\n        ${fillAttr}` : ''}`;
  return body ? `${open}>${body}</path>` : `${open} />`;
}

function vector(size, viewport, inner, aapt = false) {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by brand/build.mjs from brand/flow-reader-mark.svg. Do not edit. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"${aapt ? '\n    xmlns:aapt="http://schemas.android.com/aapt"' : ''}
    android:width="${size}dp"
    android:height="${size}dp"
    android:viewportWidth="${viewport}"
    android:viewportHeight="${viewport}">
${inner}
</vector>
`;
}

function colored(paths) {
  return paths.map((p) => {
    const f = fill(p);
    return pathXml(p.d, f.attr, f.body);
  }).join('\n');
}

/** One-colour silhouette: body with holes cut out (even-odd), plus extra solid shapes. */
function silhouette(paths, keep) {
  const kept = paths.filter(keep);
  const body = kept.filter((p) => p['data-mono'] === 'body' || p['data-mono'] === 'hole').map((p) => p.d).join(' ');
  const solids = kept.filter((p) => p['data-mono'] === 'solid').map((p) => p.d);
  return [body, ...solids]
    .filter(Boolean)
    .map((d, i) => pathXml(d, 'android:fillColor="#FFFFFFFF"', '', i === 0 ? '\n        android:fillType="evenOdd"' : ''))
    .join('\n');
}

function bounds(paths) {
  const nums = paths.flatMap((p) => [...p.d.matchAll(/(-?\d*\.?\d+),(-?\d*\.?\d+)/g)].map((m) => [+m[1], +m[2]]));
  const xs = nums.map((n) => n[0]);
  const ys = nums.map((n) => n[1]);
  return { minX: Math.min(...xs), maxX: Math.max(...xs), minY: Math.min(...ys), maxY: Math.max(...ys) };
}

const background = layer('background');
const foreground = layer('foreground');
const out = {};

out['drawable/ic_launcher_background.xml'] = vector(108, 108, colored(background), true);
out['drawable/ic_launcher_foreground.xml'] = vector(108, 108, colored(foreground), true);
out['drawable/ic_launcher_monochrome.xml'] = vector(108, 108, silhouette(foreground, () => true));

const STAT_VIEWPORT = 24;
const STAT_LIVE = 20;
const statPaths = foreground.filter((p) => p['data-stat'] !== 'skip');
const b = bounds(statPaths);
const scale = +(STAT_LIVE / Math.max(b.maxX - b.minX, b.maxY - b.minY)).toFixed(4);
const tx = +(STAT_VIEWPORT / 2 - ((b.minX + b.maxX) / 2) * scale).toFixed(3);
const ty = +(STAT_VIEWPORT / 2 - ((b.minY + b.maxY) / 2) * scale).toFixed(3);
const statInner = silhouette(statPaths, () => true).replace(/^/gm, '    ');
out['drawable/ic_stat_flow.xml'] = vector(24, STAT_VIEWPORT, `    <group
        android:scaleX="${scale}"
        android:scaleY="${scale}"
        android:translateX="${tx}"
        android:translateY="${ty}">
${statInner}
    </group>`);

out['values/brand_colors.xml'] = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by brand/build.mjs from brand/flow-reader-mark.svg. Do not edit. -->
<resources>
${Object.entries(colors).map(([k, v]) => `    <color name="brand_${k.replace(/^fr-/, '').replace(/-/g, '_')}">${argb(v)}</color>`).join('\n')}
</resources>
`;

for (const [rel, text] of Object.entries(out)) {
  const file = join(res, rel);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, text);
  console.log(`wrote app/src/main/res/${rel}`);
}
