<#
.SYNOPSIS
  Regenerate docs/agent/index.md: every Kotlin file with line count and declarations + line numbers.

.DESCRIPTION
  Top-level non-private declarations are listed for every file. Files over -MemberThreshold lines also
  list private top-level and member functions so agents can Read a slice instead of the whole file.
  Run after adding, moving, or splitting files.

.EXAMPLE
  .\scripts\gen-agent-index.ps1
  .\scripts\gen-agent-index.ps1 -Check   # exit 1 if index.md is stale
#>
param(
  [int]$MemberThreshold = 400,
  [switch]$Check
)

$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$srcRoot = Join-Path $root 'app\src\main\java\com\personal\flowreader'
$testRoot = Join-Path $root 'app\src\test\java\com\personal\flowreader'
$outPath = Join-Path $root 'docs\agent\index.md'

$mods = '(?:(?:public|internal|private|protected|data|sealed|enum|abstract|open|inline|value|annotation|suspend|const|override|operator|infix|tailrec|lateinit|fun)\s+)*'
$topDecl = [regex]"^$mods(class|object|interface|fun|val|var|typealias)\s+(?:<[^>]+>\s+)?(?:[\w.<>?, ]+\.)?(\w+)"
$memberDecl = [regex]"^    $mods(fun|class|object|interface)\s+(?:<[^>]+>\s+)?(?:[\w.<>?, ]+\.)?(\w+)"

function Get-Entries($file) {
  $lines = [IO.File]::ReadAllLines($file.FullName)
  $large = $lines.Length -gt $MemberThreshold
  $top = New-Object System.Collections.Generic.List[string]
  $members = New-Object System.Collections.Generic.List[string]
  for ($i = 0; $i -lt $lines.Length; $i++) {
    $line = $lines[$i]
    $m = $topDecl.Match($line)
    if ($m.Success) {
      $kind = $m.Groups[1].Value
      $isPrivate = $line -match '^\s*private\s'
      if (-not $isPrivate -or ($large -and $kind -notin 'val', 'var')) {
        $name = $m.Groups[2].Value
        $tag = switch ($kind) { 'class' { if ($line -match '\benum\s+class') { 'enum ' } elseif ($line -match '\bdata\s+class') { 'data ' } elseif ($line -match '\bsealed\s') { 'sealed ' } else { 'class ' } } 'interface' { 'iface ' } 'object' { 'obj ' } default { '' } }
        $top.Add("$tag$name`:$($i + 1)")
      }
      continue
    }
    if ($large) {
      $mm = $memberDecl.Match($line)
      if ($mm.Success) { $members.Add("$($mm.Groups[2].Value):$($i + 1)") }
    }
  }
  [pscustomobject]@{ Lines = $lines.Length; Top = $top; Members = $members }
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('# Code index (generated)')
[void]$sb.AppendLine()
[void]$sb.AppendLine('Generated by `scripts/gen-agent-index.ps1` - do not edit. Paths are relative to')
[void]$sb.AppendLine('`app/src/main/java/com/personal/flowreader/`. Format: `name:line`; files over')
[void]$sb.AppendLine("$MemberThreshold lines also list members, so Read with offset/limit instead of the whole file.")
[void]$sb.AppendLine('Hand-written guide: [map.md](map.md).')

$files = Get-ChildItem $srcRoot -Recurse -File -Filter *.kt | Sort-Object DirectoryName, Name
$total = 0
$currentDir = $null
foreach ($file in $files) {
  $rel = $file.FullName.Substring($srcRoot.Length + 1).Replace('\', '/')
  $dir = if ($rel.Contains('/')) { $rel.Substring(0, $rel.LastIndexOf('/')) } else { '(root)' }
  if ($dir -ne $currentDir) {
    [void]$sb.AppendLine()
    [void]$sb.AppendLine("## $dir")
    [void]$sb.AppendLine()
    $currentDir = $dir
  }
  $e = Get-Entries $file
  $total += $e.Lines
  $big = if ($e.Lines -gt $MemberThreshold) { ' **large**' } else { '' }
  $decls = if ($e.Top.Count) { ' - ' + ($e.Top -join ', ') } else { '' }
  [void]$sb.AppendLine("- ``$($file.Name)`` ($($e.Lines))$big$decls")
  if ($e.Members.Count) {
    [void]$sb.AppendLine("  - members: " + ($e.Members -join ', '))
  }
}

[void]$sb.AppendLine()
[void]$sb.AppendLine('## Tests (`app/src/test/java/com/personal/flowreader/`)')
[void]$sb.AppendLine()
Get-ChildItem $testRoot -Recurse -File -Filter *.kt | Sort-Object FullName | ForEach-Object {
  $rel = $_.FullName.Substring($testRoot.Length + 1).Replace('\', '/')
  [void]$sb.AppendLine("- ``$rel``")
}
[void]$sb.AppendLine()
[void]$sb.AppendLine("Totals: $($files.Count) main files, $total lines.")

$content = $sb.ToString().Replace("`r`n", "`n")
if ($Check) {
  $existing = if (Test-Path $outPath) { [IO.File]::ReadAllText($outPath).Replace("`r`n", "`n") } else { '' }
  if ($existing -ne $content) { Write-Error 'docs/agent/index.md is stale; run scripts/gen-agent-index.ps1'; exit 1 }
  Write-Host 'index.md up to date.'
  exit 0
}
New-Item -ItemType Directory -Force (Split-Path $outPath -Parent) | Out-Null
[IO.File]::WriteAllText($outPath, $content)
Write-Host "Wrote $outPath ($($files.Count) files, $total lines)."
